<a href="https://colab.research.google.com/github/ni-ms/colab-projects/blob/RNN/RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Things you should automatically know and memorize
# N = Number of samples
# T = sequence length
# D = number of input features
# M = Number of hidden units
# K = Number of output units

In [ ]:
# Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [ ]:
# Make an RNN
M = 5 # No. of hidden units
i = Input(shape = (T,D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)
model = Model(i,x)

In [ ]:
Yhat = model.predict(X)
print(Yhat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step
[[ 0.87460065 -0.03552376]]


In [ ]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 10, 3)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_1 (SimpleRNN)             │ (None, 5)                   │              45 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 57 (228.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.layers[1].get_weights()

[array([[ 0.00201088, -0.52320945, -0.46547493,  0.13764733,  0.66665334],
        [ 0.7610442 , -0.10042936,  0.3812819 , -0.08829886, -0.1242227 ],
        [ 0.5169793 ,  0.13470405, -0.4494569 , -0.35689634, -0.2575888 ]],
       dtype=float32),
 array([[ 0.6449901 , -0.09234317,  0.413137  ,  0.6203705 ,  0.14113404],
        [-0.21801898,  0.08772692,  0.14625126, -0.07559989,  0.9579494 ],
        [-0.5191987 , -0.5241733 , -0.252398  ,  0.6258233 ,  0.0177615 ],
        [ 0.34649917, -0.8105561 , -0.10881975, -0.43915647,  0.13504444],
        [ 0.38317955,  0.22807449, -0.8557931 ,  0.15783456,  0.20943198]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [ ]:
# Check their shapes
# Should make sense
# First output is input to hidden
# Second output is hidden to hidden
# Third output is bias term ( Vector of length M)
a,b,c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [ ]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [ ]:
# Manual RNN Calculation
h_last = np.zeros(M) # Initial hidden state
x = X[0] # One and only sample
Yhats = [] # Where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # We only care about this value in the last iteration
  Yhats.append(y)

  h_last = h

print(Yhats[-1])

[ 0.87460058 -0.03552383]


In [ ]:
# Calculate the output for multple samples at once